name: VisualTests

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
  push:
    paths-ignore:
    - 'docs/**'

jobs:

  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        edition: [ee, oss]
    env:
      MB_EDITION: ${{ matrix.edition }}
      INTERACTIVE: false
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Clojure CLI
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.708.sh &&
        sudo bash ./linux-install-1.10.1.708.sh
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java -version
        echo "Clojure `clojure -e "(println (clojure-version))"`"
        lein --version

  percy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Clojure CLI
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.708.sh &&
        sudo bash ./linux-install-1.10.1.708.sh
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java -version
        echo "Clojure `clojure -e "(println (clojure-version))"`"
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: ./bin/build version

    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: metabase-oss-uberjar
    - run: yarn run test-visual-no-build
      name: Run Percy tests
      env:
        TERM: xterm
